In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.metrics import mean_squared_error

In [2]:
data=pd.read_csv('/content/data_w3_ex1.csv')

In [3]:
data.head(4)

1.651000000000000227e+03  4.326452172406379759e+02
0               1691.816327                454.935530
1               1732.632653                471.525248
2               1773.448980                482.506389
3               1814.265306                468.357886

In [4]:
data.tail(4)

1.651000000000000227e+03  4.326452172406379759e+02
45               3528.551020                874.112598
46               3569.367347                882.803295
47               3610.183673                910.832721
48               3651.000000                897.420463

In [61]:
x=data.iloc[:,0]
y=data.iloc[:,1]

In [62]:
x=np.expand_dims(x,axis=1)
y=np.expand_dims(y,axis=1)

In [63]:
print(f"x shape: {x.shape}")
print(f"y shape: {y.shape}")

x shape: (49, 1)
y shape: (49, 1)


In [103]:
x_train,x_,y_train,y_=train_test_split(x,y,test_size=0.2,random_state=1)

In [104]:
x_cv,x_test,y_cv,y_test=train_test_split(x_,y_,test_size=0.5,random_state=1)

In [105]:
del x_,y_

In [106]:
print(f"the shape of x_train is: {x_train.shape}")
print(f"the shape of y_train is: {y_train.shape}\n")
print(f"the shape of cross validation input is : {x_cv.shape}")
print(f"the shape of cross validation target is :{y_cv.shape}\n")
print(f"the shape of test input is: {x_test.shape}")
print(f"the shape of test target is: {y_test.shape}")

the shape of x_train is: (39, 1)
the shape of y_train is: (39, 1)

the shape of cross validation input is : (5, 1)
the shape of cross validation target is :(5, 1)

the shape of test input is: (5, 1)
the shape of test target is: (5, 1)


In [107]:
scaler_linear=StandardScaler()

In [108]:
x_train_scaled=scaler_linear.fit_transform(x_train)

In [109]:
model=LinearRegression()

In [110]:
model.fit(x_train_scaled,y_train)

LinearRegression()

In [111]:
y_hat=model.predict(x_train_scaled)

In [112]:
y_hat[:5]

array([[793.14412337],
       [859.18122649],
       [698.80540463],
       [830.87961087],
       [679.93766088]])

In [113]:
from sklearn.metrics import mean_squared_error

In [114]:
print(f"the mean squared error is: {mean_squared_error(y_train,y_hat)/2}")

the mean squared error is: 324.0342074682099


In [115]:
total_error=0
for i in range (len(y_train)):
  error_i=(y_train[i]-y_hat[i])**2
  total_error+=error_i
total_error=total_error/(2*len(y_train))
print(f"the mean squared error is: {np.squeeze(total_error)}")

the mean squared error is: 324.03420746820996


In [116]:
x_cv_scaled=scaler_linear.fit_transform(x_cv)
# y_hat_cv=model.predict(x_cv_scaled)mistak
y_hat_cv=model.predict(x_cv_scaled)

In [117]:
y_hat_cv[:5]

array([[841.31748585],
       [730.28346815],
       [690.62846183],
       [817.52448205],
       [484.42242896]])

In [118]:
print(f"Mean used to scale the CV set: {scaler_linear.mean_.squeeze():.2f}")
print(f"Standard deviation used to scale the CV set: {scaler_linear.scale_.squeeze():.2f}")
print(f"the mean squared arroe of x_cv_scaled is :{mean_squared_error(y_cv,y_hat_cv)/2}")

Mean used to scale the CV set: 2989.78
Standard deviation used to scale the CV set: 652.76
the mean squared arroe of x_cv_scaled is :3020.085679821683


In [119]:
total_error=0
for i in range (len(y_cv)):
  error_i=(y_cv[i]-y_hat_cv[i])**2
  total_error+=error_i
total_error=total_error/(2*len(y_cv))
print(np.squeeze(total_error))

3020.085679821683


In [128]:
# x1=np.array([1691.816327])
# x1=np.array([1773.448980])
x1=np.array([1855.081633	])
# x1=np.array([1814.265306])
# x1=np.expand_dims(x1,axis=1)
x1_scaled=scaler_linear.transform(x1.reshape(-1,1))
y_pred=model.predict(x1_scaled)
print(f"the output without using polynomial function {np.squeeze(y_pred)}")

the output without using polynomial function 492.35343029333734


In [122]:
data.head(5)

1.651000000000000227e+03  4.326452172406379759e+02
0               1691.816327                454.935530
1               1732.632653                471.525248
2               1773.448980                482.506389
3               1814.265306                468.357886
4               1855.081633                482.152531

lets try is using polynomial **features**

In [129]:
from sklearn.preprocessing  import PolynomialFeatures

In [130]:
# poly=PolynomialFeatures(degree=2,include_bias=False)
# x_traine_mapped=poly.fit_transform(x_train)
poly=PolynomialFeatures(degree=2,include_bias=False)
x_trained_mapped=poly.fit_transform(x_train)
print(x_trained_mapped[:5])

[[2.95712245e+03 8.74457318e+06]
 [3.24283673e+03 1.05159901e+07]
 [2.54895918e+03 6.49719292e+06]
 [3.12038776e+03 9.73681974e+06]
 [2.46732653e+03 6.08770021e+06]]


In [131]:
scaler_poly=StandardScaler()
x_trained_mapped_scaled=scaler_poly.fit_transform(x_trained_mapped)
x_trained_mapped_scaled[:5]

array([[ 0.63316824,  0.55625319],
       [ 1.15381561,  1.15961867],
       [-0.11061373, -0.20923102],
       [ 0.93068102,  0.89422407],
       [-0.25937012, -0.34870907]])

In [132]:
model=LinearRegression()
model.fit(x_trained_mapped_scaled,y_train)

LinearRegression()

In [133]:
y_hat=model.predict(x_trained_mapped_scaled)

In [134]:
y_hat[:5]

array([[811.1463194 ],
       [856.49895652],
       [722.90352189],
       [838.71764022],
       [701.94390602]])

In [135]:
print(f"the mean squared arror is {mean_squared_error(y_train,y_hat)/2}")

the mean squared arror is 56.73932914746899


In [136]:
x_cv_mapped=poly.transform(x_cv)
x_cv_mapped_scaled=scaler_poly.transform(x_cv_mapped)
# model.fit(x_cv_mapped_scaled,y_cv)
y_hat_cv=model.predict(x_cv_mapped_scaled)

In [137]:
y_hat_cv[:5]

array([[897.83512223],
       [832.23869206],
       [795.7051308 ],
       [888.33144683],
       [494.53430275]])

In [138]:
print(f"Training MSE: {mean_squared_error(y_train, y_hat) / 2}")

Training MSE: 56.73932914746899


In [139]:
print(f"Cross validation MSE: {mean_squared_error(y_cv, y_hat_cv) / 2}")

Cross validation MSE: 97.05147204236603


In [140]:

train_mses = []
cv_mses = []
models = []
polys = []
scalers = []
for degree in range(1,11):

    # Add polynomial features to the training set
    poly = PolynomialFeatures(degree, include_bias=False)
    X_train_mapped = poly.fit_transform(x_train)
    polys.append(poly)

    # Scale the training set
    scaler_poly = StandardScaler()
    X_train_mapped_scaled = scaler_poly.fit_transform(X_train_mapped)
    scalers.append(scaler_poly)

    # Create and train the model
    model = LinearRegression()
    model.fit(X_train_mapped_scaled, y_train )
    models.append(model)

    # Compute the training MSE
    yhat = model.predict(X_train_mapped_scaled)
    train_mse = mean_squared_error(y_train, yhat) / 2
    train_mses.append(train_mse)

    # Add polynomial features and scale the cross validation set
    X_cv_mapped = poly.transform(x_cv)
    X_cv_mapped_scaled = scaler_poly.transform(X_cv_mapped)

    # Compute the cross validation MSE
    yhat = model.predict(X_cv_mapped_scaled)
    cv_mse = mean_squared_error(y_cv, yhat) / 2
    cv_mses.append(cv_mse)

In [141]:
degree = np.argmin(cv_mses) +1
print(f"Lowest CV MSE is found in the model with degree={degree}")

Lowest CV MSE is found in the model with degree=2


In [142]:
# Add polynomial features to the test set
X_test_mapped = polys[degree-1].transform(x_test)

# Scale the test set
X_test_mapped_scaled = scalers[degree-1].transform(X_test_mapped)

# Compute the test MSE
yhat = models[degree-1].predict(X_test_mapped_scaled)
test_mse = mean_squared_error(y_test, yhat) / 2

print(f"Training MSE: {train_mses[degree-1]:.2f}")
print(f"Cross Validation MSE: {cv_mses[degree-1]:.2f}")
print(f"Test MSE: {test_mse:.2f}")

Training MSE: 56.74
Cross Validation MSE: 97.05
Test MSE: 107.94


In [144]:
# x2=np.array([1773.448980	])
x2=np.array([2059.163265])
x2=np.expand_dims(x2,axis=1)
x2_mapped=polys[degree-1].transform(x2)
x2_mapped_scaled=scalers[degree-1].transform(x2_mapped)
y_pred=models[degree-1].predict(x2_mapped_scaled)
print(f"the output using polynomial function {np.squeeze(y_pred)}")

the output using polynomial function 580.5905447829031


In [ ]:
data.head(10)

1.651000000000000227e+03  4.326452172406379759e+02
0               1691.816327                454.935530
1               1732.632653                471.525248
2               1773.448980                482.506389
3               1814.265306                468.357886
4               1855.081633                482.152531
5               1895.897959                540.021756
6               1936.714286                534.584267
7               1977.530612                558.346208
8               2018.346939                566.423445
9               2059.163265                581.397651